# Generated by Django 3.2.4 on 2021-07-07 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-article_name'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
