# Generated by Django 3.2.4 on 2021-07-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sub_category_name'], 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
    ]
