# Generated by Django 3.2.4 on 2021-07-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210707_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['article_name'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
